name: CI

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - '*'

jobs:
  test-v1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sba-version: [ '1.4.6', '1.5.7' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Gradle run server
        run: nohup ./gradlew runV1SBAServer -Psba.version=${{ matrix.sba-version }} -Psba.server.port=8081 &

      - name: Await server up
        uses: cygnetdigital/wait_for_response@v2.0.0
        with:
          url: http://localhost:8081/health
          responseCode: 200,500
          timeout: 300000
          interval: 1000

      - name: Gradle test
        run: ./gradlew :sbapsd-testing:test -Psba.version=${{ matrix.sba-version }} -Psba.server.port=8081

  test-v2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sba-version: [ '2.4.4', '2.5.6', '2.6.11', '2.7.10' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Gradle run server
        run: nohup ./gradlew runV2SBAServer -Psba.version=${{ matrix.sba-version }} -Psba.server.port=8082 &

      - name: Await server up
        uses: cygnetdigital/wait_for_response@v2.0.0
        with:
          url: http://localhost:8082/actuator/health
          responseCode: 200,500
          timeout: 300000
          interval: 1000

      - name: Gradle test
        run: ./gradlew :sbapsd-testing:test -Psba.version=${{ matrix.sba-version }} -Psba.server.port=8082

  test-v3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sba-version: [ '3.0.0' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Gradle run server
        run: nohup ./gradlew runV3SBAServer -Psba.version=${{ matrix.sba-version }} -Psba.server.port=8083 &

      - name: Await server up
        uses: cygnetdigital/wait_for_response@v2.0.0
        with:
          url: http://localhost:8083/actuator/health
          responseCode: 200,500
          timeout: 300000
          interval: 1000

      - name: Gradle test
        run: ./gradlew :sbapsd-testing:test -Psba.version=${{ matrix.sba-version }} -Psba.server.port=8083

  build-jvm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Gradle build
        run: ./gradlew build

      - name: Upload app-jar
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: |
            sbapsd-standalone-v2/build/libs/*.jar
            sbapsd-standalone-v3/build/libs/*.jar
          retention-days: 7

  build-native:
    strategy:
      matrix:
        include:
          - name: linux
            os: ubuntu-22.04
            artifact: app-native-linux
          - name: windows
            os: windows-latest
            artifact: app-native-windows
          - name: macos
            os: macos-latest
            artifact: app-native-macos
    runs-on: ${{ matrix.os }}
    name: build-native-${{ matrix.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'liberica'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Gradle nativeCompile
        run: ./gradlew nativeCompile

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: |
            sbapsd-standalone-v3/build/native/nativeCompile
          retention-days: 7

  release:
    runs-on: ubuntu-latest
    needs: [ test-v1, test-v2, test-v3, build-jvm, build-native ]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Download Artifacts
        uses: actions/download-artifact@v5

      - name: Prepare Linux Artifacts
        run: |
          cd app-native-linux
          chmod +x sbapsd
          tar -czf $(cat gradle-artifact.txt).tar.gz sbapsd

      - name: Prepare macOS Artifacts
        run: |
          cd app-native-macos
          chmod +x sbapsd
          tar -czf $(cat gradle-artifact.txt).tar.gz sbapsd

      - name: Prepare Windows Artifacts
        run: |
          cd app-native-windows
          zip $(cat gradle-artifact.txt).zip sbapsd.exe

      - name: Build Release Changelog
        id: build-release-changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configuration: ".github/release-changelog-builder.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.build-release-changelog.outputs.changelog }}
          draft: true
          files: |
            app-jar/**/!(*-plain).jar
            app-native-linux/*.tar.gz
            app-native-macos/*.tar.gz
            app-native-windows/*.zip

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Gradle publish
        env:
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
